<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Спасибо за регистрацию</title>
    <style>
        h1 {
            color: #000030;
        }
    </style>
</head>
<h1>Ссылка на регистрацию:</h1>
<img src="http://localhost:8080/images/foremail.jpg">
<h2><a href="http://localhost:8080/confirm/${confirm_code}">Сюда</a></h2>
</body>
</html>